### ISSUE TITLE
May I ask if there is an error in the local compilation? How to solve it? thank you

### ISSUE THREAD

**Issue by hioo520** [slint-ui/slint-rust-template#9]
```
PS A:\project\day04\guog> $env:RUST_BACKTRACE='full'; cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target\debug\guog.exe`
thread 'main' panicked at 'there must be a sans-serif font face registered', X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-renderer-femtovg-1.0.0\fonts.rs:313:14
stack backtrace:
   0:     0x7ff748c5b712 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff748c5b712 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff748c5b712 - std::sys_common::backtrace::_print_fmt
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\sys_common\backtrace.rs:65
   3:     0x7ff748c5b712 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff748c7334b - core::fmt::write
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\fmt\mod.rs:1213
   5:     0x7ff748c5791a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\io\mod.rs:1682
   6:     0x7ff748c5b45b - std::sys_common::backtrace::_print
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\sys_common\backtrace.rs:47
   7:     0x7ff748c5b45b - std::sys_common::backtrace::print
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff748c5dd89 - std::panicking::default_hook::closure$1
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:267
   9:     0x7ff748c5da0b - std::panicking::default_hook
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:286
  10:     0x7ff748c5e620 - std::panicking::rust_panic_with_hook
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:688
  11:     0x7ff748c5e3ae - std::panicking::begin_panic_handler::closure$0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:579
  12:     0x7ff748c5c12f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\sys_common\backtrace.rs:137
  13:     0x7ff748c5e060 - std::panicking::begin_panic_handler
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
  14:     0x7ff748c7c6c5 - core::panicking::panic_fmt
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
  15:     0x7ff748c71d90 - core::panicking::panic_display<ref$<str$> >
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:147
  16:     0x7ff748c71d3b - core::panicking::panic_str
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:131
  17:     0x7ff748c7c689 - core::option::expect_failed
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\option.rs:1924
  18:     0x7ff7486ff9eb - enum2$<core::option::Option<fontdb::ID> >::expect<fontdb::ID>
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\option.rs:786
  19:     0x7ff74872273f - i_slint_renderer_femtovg::fonts::FontCache::load_single_font
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-renderer-femtovg-1.0.0\fonts.rs:304
  20:     0x7ff748722b81 - i_slint_renderer_femtovg::fonts::FontCache::font
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-renderer-femtovg-1.0.0\fonts.rs:362
  21:     0x7ff7487220bf - i_slint_renderer_femtovg::fonts::text_size::closure$0
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-renderer-femtovg-1.0.0\fonts.rs:145
  22:     0x7ff7486ebbc1 - std::thread::local::LocalKey<core::cell::RefCell<i_slint_renderer_femtovg::fonts::FontCache> >::try_with<core::cell::RefCell<i_slint_renderer_femtovg::fonts::FontCache>,i_slint_renderer_femtovg::fonts::text_size::closure_env$0,i_slint_renderer_femtovg::fo
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\std\src\thread\local.rs:446
  23:     0x7ff7486eb595 - std::thread::local::LocalKey<core::cell::RefCell<i_slint_renderer_femtovg::fonts::FontCache> >::with<core::cell::RefCell<i_slint_renderer_femtovg::fonts::FontCache>,i_slint_renderer_femtovg::fonts::text_size::closure_env$0,i_slint_renderer_femtovg::fonts:
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\std\src\thread\local.rs:422
  24:     0x7ff748721eee - i_slint_renderer_femtovg::fonts::text_size
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-renderer-femtovg-1.0.0\fonts.rs:145
  25:     0x7ff7486f8145 - i_slint_renderer_femtovg::impl$1::text_size
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-renderer-femtovg-1.0.0\lib.rs:218
  26:     0x7ff748652cf6 - i_slint_backend_winit::renderer::femtovg::impl$2::text_size
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-backend-winit-1.0.0\renderer\femtovg.rs:172
  27:     0x7ff7489fa063 - i_slint_core::items::text::impl$0::layout_info::closure$0
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\items\text.rs:78
  28:     0x7ff7489f9b70 - i_slint_core::items::text::impl$0::layout_info
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\items\text.rs:91
  29:     0x7ff7485ff606 - guog::slint_generatedAppWindow::impl$9::init::closure$3
                               at A:\project\day04\guog\target\debug\build\guog-b4f6c303cb277a24\out\appwindow.rs:1026
  30:     0x7ff748605b02 - core::ops::function::FnOnce::call_once<guog::slint_generatedAppWindow::impl$9::init::closure_env$3,tuple$<vtable::vrc::VRcMapped<i_slint_core::component::Component_vtable_mod::ComponentVTable,guog::slint_generatedAppWindow::InnerAppWindow> > >
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:250
  31:     0x7ff7485f1a97 - slint::private_unstable_api::set_property_binding::closure$0<i_slint_core::layout::LayoutInfo,vtable::vrc::VRcMapped<i_slint_core::component::Component_vtable_mod::ComponentVTable,guog::slint_generatedAppWindow::InnerAppWindow> >
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\slint-1.0.0\private_unstable_api.rs:61
  32:     0x7ff7485f1dab - i_slint_core::properties::impl$4::evaluate<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::LayoutInfo,vtable::vrc::VRcMapped<i_slint_core::component::Component_vtable_mod::ComponentVT
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:689
  33:     0x7ff7486245a8 - i_slint_core::properties::impl$7::set_binding::closure$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::LayoutInfo,vtable::vrc::VRcMapped<i_slint_core::component::Component_vtable_mo
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:882
  34:     0x7ff748629474 - i_slint_core::properties::impl$0::evaluate<i_slint_core::properties::impl$7::set_binding::closure_env$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::LayoutInfo,vtable::vrc::VRcMapp
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:288
  35:     0x7ff748628c70 - i_slint_core::properties::alloc_binding_holder::evaluate::closure$0<i_slint_core::properties::impl$7::set_binding::closure_env$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::Layout
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:391
  36:     0x7ff74862364e - i_slint_core::properties::CURRENT_BINDING::set<i_slint_core::properties::alloc_binding_holder::evaluate::closure_env$0<i_slint_core::properties::impl$7::set_binding::closure_env$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\scoped-tls-hkt-0.1.2\src\lib.rs:264
  37:     0x7ff74862835b - i_slint_core::properties::alloc_binding_holder::evaluate<i_slint_core::properties::impl$7::set_binding::closure_env$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::LayoutInfo,vtable
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:390
  38:     0x7ff748621fe1 - i_slint_core::properties::impl$2::update::closure$0<i_slint_core::layout::LayoutInfo>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:574
  39:     0x7ff7486215c7 - i_slint_core::properties::PropertyHandle::access<bool,i_slint_core::properties::impl$2::update::closure_env$0<i_slint_core::layout::LayoutInfo> >
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:479
  40:     0x7ff748621d27 - i_slint_core::properties::PropertyHandle::update<i_slint_core::layout::LayoutInfo>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:569
  41:     0x7ff7486250c2 - i_slint_core::properties::Property<i_slint_core::layout::LayoutInfo>::get<i_slint_core::layout::LayoutInfo>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:773
  42:     0x7ff748600095 - guog::slint_generatedAppWindow::impl$9::init::closure$5
                               at A:\project\day04\guog\target\debug\build\guog-b4f6c303cb277a24\out\appwindow.rs:1138
  43:     0x7ff7486066d2 - core::ops::function::FnOnce::call_once<guog::slint_generatedAppWindow::impl$9::init::closure_env$5,tuple$<vtable::vrc::VRcMapped<i_slint_core::component::Component_vtable_mod::ComponentVTable,guog::slint_generatedAppWindow::InnerAppWindow> > >
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:250
  44:     0x7ff7485f1a97 - slint::private_unstable_api::set_property_binding::closure$0<i_slint_core::layout::LayoutInfo,vtable::vrc::VRcMapped<i_slint_core::component::Component_vtable_mod::ComponentVTable,guog::slint_generatedAppWindow::InnerAppWindow> >
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\slint-1.0.0\private_unstable_api.rs:61
  45:     0x7ff7485f1dab - i_slint_core::properties::impl$4::evaluate<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::LayoutInfo,vtable::vrc::VRcMapped<i_slint_core::component::Component_vtable_mod::ComponentVT
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:689
  46:     0x7ff7486245a8 - i_slint_core::properties::impl$7::set_binding::closure$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::LayoutInfo,vtable::vrc::VRcMapped<i_slint_core::component::Component_vtable_mo
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:882
  47:     0x7ff748629474 - i_slint_core::properties::impl$0::evaluate<i_slint_core::properties::impl$7::set_binding::closure_env$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::LayoutInfo,vtable::vrc::VRcMapp
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:288
  48:     0x7ff748628c70 - i_slint_core::properties::alloc_binding_holder::evaluate::closure$0<i_slint_core::properties::impl$7::set_binding::closure_env$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::Layout
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:391
  49:     0x7ff74862364e - i_slint_core::properties::CURRENT_BINDING::set<i_slint_core::properties::alloc_binding_holder::evaluate::closure_env$0<i_slint_core::properties::impl$7::set_binding::closure_env$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\scoped-tls-hkt-0.1.2\src\lib.rs:264
  50:     0x7ff74862835b - i_slint_core::properties::alloc_binding_holder::evaluate<i_slint_core::properties::impl$7::set_binding::closure_env$0<i_slint_core::layout::LayoutInfo,slint::private_unstable_api::set_property_binding::closure_env$0<i_slint_core::layout::LayoutInfo,vtable
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:390
  51:     0x7ff748621fe1 - i_slint_core::properties::impl$2::update::closure$0<i_slint_core::layout::LayoutInfo>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:574
  52:     0x7ff7486215c7 - i_slint_core::properties::PropertyHandle::access<bool,i_slint_core::properties::impl$2::update::closure_env$0<i_slint_core::layout::LayoutInfo> >     
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:479
  53:     0x7ff748621d27 - i_slint_core::properties::PropertyHandle::update<i_slint_core::layout::LayoutInfo>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:569
  54:     0x7ff7486250c2 - i_slint_core::properties::Property<i_slint_core::layout::LayoutInfo>::get<i_slint_core::layout::LayoutInfo>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\properties.rs:773
  55:     0x7ff7485e96ce - guog::slint_generatedAppWindow::InnerAppWindow::layout_info
                               at A:\project\day04\guog\target\debug\build\guog-b4f6c303cb277a24\out\appwindow.rs:1364
  56:     0x7ff7485ea663 - guog::slint_generatedAppWindow::impl$12::layout_info
                               at A:\project\day04\guog\target\debug\build\guog-b4f6c303cb277a24\out\appwindow.rs:1515
  57:     0x7ff748601788 - guog::slint_generatedAppWindow::impl$11::drop::VT::layout_info<guog::slint_generatedAppWindow::InnerAppWindow>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\component.rs:41
  58:     0x7ff7489aa0cd - i_slint_core::component::Component_vtable_mod::ComponentTO::layout_info
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\component.rs:41
  59:     0x7ff74866324a - i_slint_backend_winit::glwindow::impl$3::show::closure$0<i_slint_backend_winit::renderer::femtovg::GlutinFemtoVGRenderer>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-backend-winit-1.0.0\glwindow.rs:492
  60:     0x7ff7486411ba - core::ops::function::FnOnce::call_once<i_slint_backend_winit::glwindow::impl$3::show::closure_env$0<i_slint_backend_winit::renderer::femtovg::GlutinFemtoVGRenderer>,tuple$<ref$<i_slint_backend_winit::glwindow::GLWindow<i_slint_backend_winit::renderer::fem
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:250
  61:     0x7ff7486616e9 - i_slint_backend_winit::glwindow::GLWindow<i_slint_backend_winit::renderer::femtovg::GlutinFemtoVGRenderer>::call_with_event_loop<i_slint_backend_winit::renderer::femtovg::GlutinFemtoVGRenderer>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-backend-winit-1.0.0\glwindow.rs:199
  62:     0x7ff748662c4d - i_slint_backend_winit::glwindow::impl$3::show<i_slint_backend_winit::renderer::femtovg::GlutinFemtoVGRenderer>
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-backend-winit-1.0.0\glwindow.rs:448
  63:     0x7ff7489a908b - i_slint_core::window::WindowInner::show
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\window.rs:627
  64:     0x7ff7489c6926 - i_slint_core::api::Window::show
                               at X:\Users\XT\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\i-slint-core-1.0.0\api.rs:347
  65:     0x7ff7485eac92 - guog::slint_generatedAppWindow::impl$15::show
                               at A:\project\day04\guog\target\debug\build\guog-b4f6c303cb277a24\out\appwindow.rs:1570
  66:     0x7ff7485ea9c8 - guog::slint_generatedAppWindow::impl$15::run
                               at A:\project\day04\guog\target\debug\build\guog-b4f6c303cb277a24\out\appwindow.rs:1565
  67:     0x7ff74861fe1b - guog::main
                               at A:\project\day04\guog\src\main.rs:12
  68:     0x7ff748605963 - core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<i_slint_core::api::PlatformError> > > (*)(),tuple$<> >
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:250
  69:     0x7ff7485fa316 - std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,enum2$<i_slint_core::api::PlatformError> > > (*)(),enum2$<core::result::Result<tuple$<>,enum2$<i_slint_core::api::PlatformError> > > >
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\std\src\sys_common\backtrace.rs:121
  70:     0x7ff748619846 - std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,enum2$<i_slint_core::api::PlatformError> > > >
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\std\src\rt.rs:166
  71:     0x7ff748c53b4e - core::ops::function::impls::impl$2::call_once
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\ops\function.rs:287
  72:     0x7ff748c53b4e - std::panicking::try::do_call
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:483
  73:     0x7ff748c53b4e - std::panicking::try
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:447
  74:     0x7ff748c53b4e - std::panic::catch_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panic.rs:140
  75:     0x7ff748c53b4e - std::rt::lang_start_internal::closure$2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\rt.rs:148
  76:     0x7ff748c53b4e - std::panicking::try::do_call
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:483
  77:     0x7ff748c53b4e - std::panicking::try
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:447
  78:     0x7ff748c53b4e - std::panic::catch_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panic.rs:140
  79:     0x7ff748c53b4e - std::rt::lang_start_internal
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\rt.rs:148
  80:     0x7ff74861981a - std::rt::lang_start<enum2$<core::result::Result<tuple$<>,enum2$<i_slint_core::api::PlatformError> > > >
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\std\src\rt.rs:165
  81:     0x7ff74861fe79 - main
  82:     0x7ff748c7a8b0 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  83:     0x7ff748c7a8b0 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  84:     0x7fffed3b269d - BaseThreadInitThunk
  85:     0x7fffed6ea9f8 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\guog.exe` (exit code: 101)
```

**Comment by tronical** [comment]
Hi! This panic indicates that there's no "Arial" font in your Windows installation. That's.... very odd. Are you compiling this in some kind of restricted environment or windows container?

**Comment by hioo520** [comment]
May I know which font it is? Is Microsoft Sans Serif okay?

**Comment by tronical** [comment]
It would be "Arial". But I've never seen a Windows installation where there's no "Arial", so I'm very curious how to reproduce this situation :-)

**Comment by ogoffart** [comment]
Closing this issue here.
Feel free to use https://github.com/slint-ui/slint/discussions if you have further questions.
